name: ❓ 支持与提问
description: 提出一个问题或寻求帮助，请先查看常见问题及搜索 Issue 列表中有无你要提的问题。
title: '[Question]: '
body:
  - type: checkboxes
    id: check-answer
    attributes:
      label: 解决方案检查
      description: 请确保你已完成以下所有操作。
      options:
        - label: 我已阅读 [常见问题](https://lyswhut.github.io/lx-music-doc/mobile/faq)，但没有找到解决方案。
          required: true
        - label: 我已搜索 [Issue 列表](https://github.com/WalnutBai/lx-n-music-mobile-pro/issues?q=is%3Aissue+)，但没有发现类似的问题。
          required: true
  - type: textarea
    id: question-description
    attributes:
      label: 问题描述
      description: 请清晰简洁地描述你需要解答或协助的问题。
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: LX-X Music 版本
      description: 你使用什么版本的 LX-X Music？（如果与你的问题有关）
      placeholder: 例如 1.6.0 arm64-v8a
    validations:
      required: true
  - type: input
    id: operating-system-version
    attributes:
      label: 操作系统版本
      description: 你使用什么版本的操作系统？（如果与你的问题有关）
      placeholder: 例如 Android 15
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: 附加信息
      description: 如果你的问题需要进一步解释，或者想要补充其他截图信息，请在此处添加。（直接把图片/视频拖到编辑框即可添加图片/视频）
