const defaultSetting: LX.AppSetting = {
  version: '2.0',
  'version.autoCheckUpdate': true,
  'common.isAutoTheme': false,
  'common.langId': null,
  'common.apiSource': '',
  'common.sourceNameType': 'alias',
  'common.shareType': 'system',
  'common.isAgreePact': true,
  'common.autoHidePlayBar': true,
  'common.drawerLayoutPosition': 'left',
  'common.homePageScroll': true,
  'common.showBackBtn': false,
  'common.showExitBtn': false,
  'common.useSystemFileSelector': true,
  'common.wy_cookie': '',
  'common.wy_serpapi_key': '',
  'common.yt_cookie': '',
  'common.alwaysKeepStatusbarHeight': false,
  'common.isShowStartupGreeting': true,
  'common.hideNavigationBar': false,
  'common.isEnableLog': true,
  'common.isEnableSyncLog': false,
  'common.isEnableUserApiLog': false,
  'common.isEnableWebDAVLog': false,
  'common.isEnableSearchLog': false,
  'common.isEnablePlayerLog': false,
  'common.bilibili_multi_page': false,

  'common.navStatus': {
    nav_songlist: true,
    nav_top: true,
    nav_love: true,
    nav_daily_rec: true,
    nav_my_playlist: true,
    nav_followed_artists: true,
    nav_subscribed_albums: true,
    nav_onedrive: true,
    nav_webdav: true,
  },

  'common.navOrder': [
    'nav_search',
    'nav_play_history',
    'nav_songlist',
    'nav_top',
    'nav_love',
    'nav_daily_rec',
    'nav_followed_artists',
    'nav_subscribed_albums',
    'nav_my_playlist',
    'nav_onedrive',
    'nav_webdav',
    'nav_setting',
  ],

  'common.sectionExpandedStatus': {
    setting_player: true,
    setting_lyricDesktop: true,
    setting_download: true,
    setting_theme: true,
    setting_sync: true,
    setting_search: true,
    setting_list: true,
    setting_basic: true,
    setting_other: true,
    setting_backup: true,
    setting_about: true,
    setting_version: true,
    setting_basic_nav_menu: true,
    setting_basic_source_user_api: true,
  },

  'player.startupAutoPlay': false,
  'player.startupPushPlayDetailScreen': false,
  'player.togglePlayMethod': 'listLoop',
  'player.playQuality': '320k',
  'player.isSavePlayTime': false,
  'player.isSwipeToShowPlaylist': true,
  'player.volume': 1,
  'player.playbackRate': 1,
  'player.cacheSize': '1024',
  'player.timeoutExit': '',
  'player.timeoutExitPlayed': true,
  'player.isAutoCleanPlayedList': false,
  'player.isHandleAudioFocus': true,
  'player.isEnableAudioOffload': true,
  'player.isShowLyricTranslation': true,
  'player.isShowLyricRoma': false,
  'player.isShowNotificationImage': true,
  'player.isS2t': true,
  'player.isShowBluetoothLyric': false,

  'playDetail.isCoverSpin': true,
  'playDetail.style.align': 'center',
  'playDetail.vertical.style.lrcFontSize': 200,
  'playDetail.horizontal.style.lrcFontSize': 220,
  'playDetail.isShowLyricProgressSetting': true,

  'desktopLyric.enable': false,
  'desktopLyric.isLock': false,
  'desktopLyric.width': 100,
  'desktopLyric.maxLineNum': 5,
  'desktopLyric.isSingleLine': false,
  'desktopLyric.showToggleAnima': true,
  'desktopLyric.position.x': 0,
  'desktopLyric.position.y': 0,
  'desktopLyric.textPosition.x': 'center',
  'desktopLyric.textPosition.y': 'center',
  'desktopLyric.style.fontSize': 180,
  'desktopLyric.style.opacity': 100,
  'desktopLyric.style.lyricUnplayColor': 'rgba(255, 255, 255, 1)',
  'desktopLyric.style.lyricPlayedColor': 'rgba(7, 197, 86, 1)',
  'desktopLyric.style.lyricShadowColor': 'rgba(0, 0, 0, 0.6)',

  'search.isShowHotSearch': false,
  'search.isShowHistorySearch': true,

  'list.isClickPlayList': false,
  'list.isShowSource': true,
  'list.isShowAlbumName': true,
  'list.isShowInterval': true,
  'list.isSaveScrollLocation': true,
  'list.addMusicLocationType': 'top',
  'list.isShowMyListSubMenu': false,
  'list.isAutoSaveDailyRec': true,
  'list.isShowCover': true,

  'menu.playLater': true,
  'menu.addTo': true,
  'menu.share': true,
  'menu.playMV': true,
  'menu.songDetail': true,
  'menu.dislike': true,

  'menu.moveTo': true,
  'menu.changePosition': true,
  'menu.changeSource': true,
  'artistDetail.albumViewMode': 'grid',

  'download.enable': true,
  'download.path': '',
  'download.fileName': '歌名 - 歌手',
  'download.writeLyric': false,
  'download.writeRomaLyric': false,
  'download.writeEmbedLyric': true,
  'download.writeMetadata': true,
  'download.writePicture': true,
  'download.writeAlias': false,

  'sync.enable': false,
  'sync.webdav.enable': false,
  'sync.webdav.syncLists': false,
  'sync.webdav.url': '',
  'sync.webdav.username': '',
  'sync.webdav.password': '',
  'webdav.downloadPath': '',
  'sync.webdav.path': '/LX_Music/',
  'sync.webdav.lastSyncTimeLists': 0,

  'theme.id': 'green',
  'theme.lightId': 'green',
  'theme.darkId': 'black',
  'theme.hideBgDark': false,
  'theme.dynamicBg': true,
  'theme.blur': 18,
  'theme.fontShadow': false,
  'theme.customBgPicPath': '',
  'theme.picOpacity': 76,
  'theme.sectionOpacity': 50,
  'theme.subContainerOpacity': 50,
}

// 使用新年皮肤
if (new Date().getMonth() < 2) {
  defaultSetting['theme.id'] = 'happy_new_year'
  defaultSetting['desktopLyric.style.lyricPlayedColor'] = 'rgba(255, 18, 34, 1)'
}

export default defaultSetting
